algoritmo "Exercicio3-SomadeInteiros"
var
 val1, val2, soma: Inteiro
inicio
      escreval("<===============================>")
      escreva("Digite o primeiro valor: ")
      leia(val1)
      escreva("Digite o segundo valor: ")
      leia(val2)
      soma <- val1 + val2
      escreval("A soma entre", val1, " e", val2, " é igual a", soma)
      escreva("<===============================>")
fimalgoritmo