Algoritmo "Exercicio12-AnteSuce"

Var
   number: inteiro
Inicio
   escreval("<========================================>")
   escreval("Sucessor e antecessor de um número inteiro")
   escreval("<========================================>")
   escreva("Digite um número inteiro: ")
   leia(number)
   escreval("O antecessor é: ", number-1)
   escreval("O número digitado é: ", number)
   escreval("O número sucessor é: ", number+1)
Fimalgoritmo